import { chmod, mkdir, writeFile } from "node:fs/promises";
import { analyzeMetafile, build } from "esbuild";

const entryPoint = "src/cli.ts";
const outfile = "bin/pushgate.mjs";
const buildScript = "scripts/build-runner.mjs";
const analysisDir = "dist/bundle-analysis";
const metafilePath = `${analysisDir}/pushgate-metafile.json`;
const analysisPath = `${analysisDir}/pushgate-analysis.txt`;
const shouldAnalyze = process.argv.includes("--analyze") ||
  process.argv.includes("--metafile");

const result = await build({
  banner: {
    js: [
      "#!/usr/bin/env node",
      `// Generated by ${buildScript}.`,
      `// Source entry point: ${entryPoint}.`,
      "// Regenerate with: pnpm run bundle.",
      "// Do not edit this file directly; edit src/ instead.",
      'import { createRequire as __pushgateCreateRequire } from "node:module";',
      "const require = __pushgateCreateRequire(import.meta.url);",
    ].join("\n"),
  },
  bundle: true,
  entryPoints: [entryPoint],
  format: "esm",
  loader: {
    ".md": "text",
  },
  logLevel: "info",
  metafile: shouldAnalyze,
  outfile,
  platform: "node",
  target: "node20",
});

await chmod(outfile, 0o755);

if (shouldAnalyze && result.metafile) {
  const analysis = await analyzeMetafile(result.metafile, {
    color: false,
    verbose: true,
  });

  await mkdir(analysisDir, { recursive: true });
  await writeFile(metafilePath, `${JSON.stringify(result.metafile, null, 2)}\n`);
  await writeFile(analysisPath, analysis);

  console.log(`Bundle metafile written to ${metafilePath}`);
  console.log(`Bundle analysis written to ${analysisPath}`);
}
